/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_aplex_jnidemo_JniNative */

#ifndef _Included_com_example_aplex_jnidemo_JniNative
#define _Included_com_example_aplex_jnidemo_JniNative
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_aplex_jnidemo_JniNative
 * Method:    sayHelloToC
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_example_aplex_jnidemo_JniNative_sayHelloToC
  (JNIEnv *, jclass, jstring);

/*
 * Class:     com_example_aplex_jnidemo_JniNative
 * Method:    HelloFromC
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_example_aplex_jnidemo_JniNative_HelloFromC
  (JNIEnv *, jclass);

/*
 * Class:     com_example_aplex_jnidemo_JniNative
 * Method:    callMethod1
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_example_aplex_jnidemo_JniNative_callMethod1
  (JNIEnv *, jclass);

/*
 * Class:     com_example_aplex_jnidemo_JniNative
 * Method:    callMethod2
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_example_aplex_jnidemo_JniNative_callMethod2
  (JNIEnv *, jclass);

/*
 * Class:     com_example_aplex_jnidemo_JniNative
 * Method:    callMethod3
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_example_aplex_jnidemo_JniNative_callMethod3
  (JNIEnv *, jclass);

/*
 * Class:     com_example_aplex_jnidemo_JniNative
 * Method:    init
 * Signature: (Ljava/lang/String;ILjava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_example_aplex_jnidemo_JniNative_init
  (JNIEnv *, jclass, jstring, jint, jstring);

/*
 * Class:     com_example_aplex_jnidemo_JniNative
 * Method:    destory
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_example_aplex_jnidemo_JniNative_destory
  (JNIEnv *, jclass);

/*
 * Class:     com_example_aplex_jnidemo_JniNative
 * Method:    call
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_example_aplex_jnidemo_JniNative_call
  (JNIEnv *, jclass, jstring);

/*
 * Class:     com_example_aplex_jnidemo_JniNative
 * Method:    hangUp
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_example_aplex_jnidemo_JniNative_hangUp
  (JNIEnv *, jclass, jstring);

/*
 * Class:     com_example_aplex_jnidemo_JniNative
 * Method:    answer
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_example_aplex_jnidemo_JniNative_answer
  (JNIEnv *, jclass, jstring);

/*
 * Class:     com_example_aplex_jnidemo_JniNative
 * Method:    refuse
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_example_aplex_jnidemo_JniNative_refuse
  (JNIEnv *, jclass, jstring);

#ifdef __cplusplus
}
#endif
#endif
