/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
/* Header for class com_example_aplex_jnidemo_JniNative */

#ifndef _Included_com_example_aplex_jnidemo_JniNative
#define _Included_com_example_aplex_jnidemo_JniNative

#include "android/log.h"
static const char *TAG="JNIDEMO";
#define LOGE(fmt, args...) __android_log_print(ANDROID_LOG_ERROR, TAG, fmt, ##args)

#include "hx/test.h"

#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_aplex_jnidemo_JniNative
 * Method:    sayHelloToC
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_example_aplex_jnidemo_JniNative_sayHelloToC
        (JNIEnv * env, jclass clazz,jstring hellostring){
        char* pStr = NULL;

        jclass     jstrObj   = (*env)->FindClass(env, "java/lang/String");
        jstring    encode    = (*env)->NewStringUTF(env, "utf-8");
        jmethodID  methodId  = (*env)->GetMethodID(env, jstrObj, "getBytes", "(Ljava/lang/String;)[B");
        jbyteArray byteArray = (jbyteArray)(*env)->CallObjectMethod(env, hellostring, methodId, encode);
        jsize      strLen    = (*env)->GetArrayLength(env, byteArray);
        jbyte      *jBuf     = (*env)->GetByteArrayElements(env, byteArray, JNI_FALSE);
        if (jBuf > 0)
        {
                pStr = (char*)malloc(strLen + 1);

                if (!pStr)
                {
                        return;
                }
                memcpy(pStr, jBuf, strLen);

                pStr[strLen] = 0;
        }
        LOGE("%s",pStr);
        (*env)->ReleaseByteArrayElements(env, byteArray, jBuf, 0);

}

/*
 * Class:     com_example_aplex_jnidemo_JniNative
 * Method:    HelloFromC
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_example_aplex_jnidemo_JniNative_HelloFromC
        (JNIEnv * env, jclass clazz){
        char * hello = "hello111";
        return  (*env)->NewStringUTF(env,hello);
}



JNIEXPORT void JNICALL Java_com_example_aplex_jnidemo_JniNative_callMethod1(JNIEnv * env,jobject obj){
        //在C语言中调用Java的空方法
        //1.找到java代码native方法所在的字节码文件
        //jclass (*FindClass)(JNIEnv*, const char*);
        jclass myclazz = (*env)->FindClass(env, "com/example/aplex/jnidemo/JniNative");
        if(myclazz == 0){
            LOGE("find class error");
            return;
        }
        LOGE("find class");
        //2.找到class里面对应的方法
        // jmethodID (*GetMethodID)(JNIEnv*, jclass, const char*, const char*);
        jmethodID method1 = (*env)->GetStaticMethodID(env,myclazz,"nullMethod","()V");
        if(method1 == 0){
            LOGE("find method1 error");
            return;
        }
        LOGE("find method1");
        //3.调用方法
        //void (*CallVoidMethod)(JNIEnv*, jobject, jmethodID, ...);
        (*env)->CallStaticVoidMethod(env, obj, method1);
        LOGE("method1 called");
}

JNIEXPORT void JNICALL Java_com_example_aplex_jnidemo_JniNative_callMethod2(JNIEnv * env, jobject obj) {
    //1.找到java代码native方法所在的字节码文件
    //jclass (*FindClass)(JNIEnv*, const char*);
    jclass clazz = (*env)->FindClass(env, "com/example/aplex/jnidemo/JniNative");
    if(clazz == 0){
        LOGE("find class error");
        return;
    }
    LOGE("find class");
    //2.找到class里面对应的方法
    // jmethodID (*GetMethodID)(JNIEnv*, jclass, const char*, const char*);
    jmethodID method2 = (*env)->GetStaticMethodID(env,clazz,"Add","(II)I");
    if(method2 == 0){
        LOGE("find method2 error");
        return;
    }
    LOGE("find method2");
    //3.调用方法
    //jint (*CallIntMethod)(JNIEnv*, jobject, jmethodID, ...);
    int result = (*env)->CallStaticIntMethod(env, obj, method2, 3,5);
    LOGE("result in C = %d", result);
}

JNIEXPORT void JNICALL Java_com_example_aplex_jnidemo_JniNative_callMethod3(JNIEnv * env, jobject obj) {
    //1.找到java代码native方法所在的字节码文件
    //jclass (*FindClass)(JNIEnv*, const char*);
    jclass clazz = (*env)->FindClass(env, "com/example/aplex/jnidemo/JniNative");
    if(clazz == 0){
        LOGE("find class error");
        return;
    }
    LOGE("find class");
    //2.找到class里面对应的方法
    // jmethodID (*GetMethodID)(JNIEnv*, jclass, const char*, const char*);
    jmethodID method3 = (*env)->GetStaticMethodID(env,clazz,"printString","(Ljava/lang/String;)V");
    if(method3 == 0){
        LOGE("find method3 error");
        return;
    }
    LOGE("find method3");
    //3.调用方法
    //void (*CallVoidMethod)(JNIEnv*, jobject, jmethodID, ...);
    (*env)->CallStaticVoidMethod(env, obj, method3,(*env)->NewStringUTF(env,"haha in C ."));
    LOGE("method3 called");

    LOGE("==============method3 called================");

    char* chhe=hello();

    LOGE("==============method3 called============");

}



#ifdef __cplusplus
}
#endif
#endif
